#pragma once

static inline void _alifUStr_initStaticStrings(AlifInterpreter* interp) {
	AlifObject* string{};

	string = &ALIF_ID(CANCELLED);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(AlifRepr);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__abstractMethods__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__annotate__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__bases__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__buildClass__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__builtins__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__class__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classCell__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classDict__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classDictCell__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classGetItem__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__complex__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__dictOffset__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__doc__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__eq__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__file__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__firstLineno__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__getAttr__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__hash__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__initSubclass__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__instanceCheck__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__IOBaseClosed);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__lengthHint__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__mroEntries__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__new__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__notes__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__origClass__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__path__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__package__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__prepare__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__setName__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__slots__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__staticAttributes__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__subClassCheck__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__typeParams__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__weakListOffset__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__weakRef__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_blksize);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_deallocWarn);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_fieldTypes);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_isTextEncoding);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_isAttyOpenOnly);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_WindowsConsoleIO);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Buffer);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Buffering);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(buffersize);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Closed);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(CloseFD);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Code);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Decode);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Decoder);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Encode);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Encoding);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(EndColOffset);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(EndLineno);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(EndOffset);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Errors);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(File);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Filename);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Fileno);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(GenExpr);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(GetState);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(HasLocation);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Join);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Key);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(keys);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(LastExc);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(LastTraceback);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(LastType);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(LastValue);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(LineBuffering);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Lineno);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(ListComp);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(MetaClass);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Mode);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Mro);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Msg);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Newline);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(NFields);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(NSequenceFields);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Offset);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Opener);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Origin);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Peek);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(PrintFileAndLine);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Readable);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Read);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Read1);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(ReadAll);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(ReadInto);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Reset);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Reverse);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Seekable);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Stderr);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Stdin);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(strict);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Text);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Top);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Translate);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Writable);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(WriteThrough);
	_alifUStr_internStatic(interp, &string);


	string = &ALIF_STR(_windowsConsoleIO);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(_findAndLoad);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(_initializing);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonGenExpr);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonLambda);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonListComp);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonSetComp);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonDictComp);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonModule);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonString);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Builtins);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(DblPercent);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Defaults);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(DotLocals);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Empty);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(utf_8);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Excepthook);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Format);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(GenericBase);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(IsAtty);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(KWDefaults);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(TypeParams);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(True);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(False);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Flush);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(ListErr);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(lambda);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Mode);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Name);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Obj);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Open);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(ReadLine);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Read);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Close);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Replace);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Raw);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(End);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Sep);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Stdout);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(TextIOWrapper);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Write);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__abs__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__add__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__call__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__format__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__init__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__import__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__loader__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__mul__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__module__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__neg__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__name__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__pow__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__qualname__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__rpow__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__radd__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__repr__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__reversed__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__rmul__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__rsub__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__sub__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__main__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__dict__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__spec__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Path);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(_io);
	_alifUStr_internStatic(interp, &string);
}
